# config.py

THRESHOLDS = {
    'MARKS_FAILING': 40, 'MARKS_BORDERLINE': 55, 'MARKS_GOOD': 70,
    'ATTENDANCE_CRITICAL': 65, 'ATTENDANCE_POOR': 75,
    'SCORE_DROP_SIGNIFICANT': 25, 'SCORE_DROP_MODERATE': 15,
    'PREVIOUS_SCORE_HIGH': 85, 'STUDY_HOURS_HIGH': 4, 'STUDY_HOURS_LOW': 1,
}